### ISSUE TITLE
meta: Bridge support from solana and Base

### ISSUE THREAD

**Issue by lucasege** [InfinityVM/InfinityVM#404]
We need to deploy a bridge for users to move funds from Solana and Base to Infinity.

This may use Hyperlane to start, but we still need to (once our testnet is stable):

- [ ] Deploy Hyperlane contracts + connectors
- [ ] Deploy or request Hyperlane relayers set up
- [ ] Configure the bridge on Infinity to connect directly to the exchange

**Comment by lucasege** [comment]
blocked until testnet release

**Comment by emostov** [comment]
@lucasege is this issue up to date given the current progress?
